import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    appContainer: {
        flex: 1,
        backgroundColor: '#f3f4f6',
        paddingTop: 40,
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
    },
    detailScrollContent: {
        padding: 20,
        paddingBottom: 100,
    },
    screenPadding: {
        padding: 20,
        flex: 1,
    },
    card: {
        width: '100%',
        maxWidth: 400,
        padding: 20,
        backgroundColor: 'white',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 3,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center',
        color: '#1f2937',
        marginBottom: 20,
        marginTop: 10,
    },
    input: {
        width: '100%',
        padding: 12,
        marginBottom: 15,
        backgroundColor: '#f9fafb',
        borderWidth: 1,
        borderColor: '#d1d5db',
        borderRadius: 8,
        fontSize: 16,
    },
    errorText: {
        color: '#ef4444',
        textAlign: 'center',
        marginBottom: 10,
    },
    messageText: {
        color: '#10b981',
        textAlign: 'center',
        marginBottom: 10,
        fontWeight: 'bold',
    },
    profileContainer: {
        flex: 1,
        padding: 20,
        alignItems: 'center',
    },
    profileTitle: {
        fontSize: 30,
        fontWeight: 'bold',
        color: '#1f2937',
        marginBottom: 20,
        marginTop: 20,
    },
    profileCard: {
        width: '100%',
        maxWidth: 400,
        padding: 20,
        backgroundColor: 'white',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 3,
        alignItems: 'center',
    },
    profileImage: {
        width: 100,
        height: 100,
        borderRadius: 50,
        marginBottom: 15,
        backgroundColor: '#e5e7eb',
    },
    profileImageLarge: {
        width: 150,
        height: 150,
        borderRadius: 75,
        marginBottom: 15,
        backgroundColor: '#e5e7eb',
    },
    profileName: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#1f2937',
    },
    profileEmail: {
        fontSize: 16,
        color: '#6b7280',
        marginBottom: 20,
    },

    searchBar: {
        flexDirection: 'row',
        marginBottom: 15,
    },
    searchInput: {
        flex: 1,
        padding: 12,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#d1d5db',
        borderTopLeftRadius: 8,
        borderBottomLeftRadius: 8,
        fontSize: 16,
    },
    searchButton: {
        borderRadius: 0,
        borderTopRightRadius: 8,
        borderBottomRightRadius: 8,
        marginTop: 0,
        paddingHorizontal: 20,
    },
    loading: {
        marginTop: 50,
    },
    resultsList: {
        flex: 1,
    },
    detailCard: {
        backgroundColor: 'white',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 3,
        padding: 20,
    },
    detailPoster: {
        width: '100%',
        height: 300,
        borderRadius: 8,
        marginBottom: 15,
        backgroundColor: '#e5e7eb',
    },
    detailTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1f2937',
        marginBottom: 10,
    },
    detailOverview: {
        fontSize: 15,
        color: '#4b5563',
        lineHeight: 22,
        marginBottom: 20,
    },
    ratingBox: {
        backgroundColor: '#f9fafb',
        padding: 15,
        borderRadius: 8,
        marginBottom: 15,
    },
    ratingLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1f2937',
        marginBottom: 5,
    },
    ratingInput: {
        padding: 10,
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: '#d1d5db',
        borderRadius: 8,
        fontSize: 16,
    },
    emptyList: {
        padding: 40,
        backgroundColor: 'white',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 3,
        alignItems: 'center',
        marginTop: 20,
    },
    emptyText: {
        fontSize: 16,
        color: '#6b7280',
        marginBottom: 20,
        textAlign: 'center',
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1f2937',
        marginBottom: 16,
    },
    detailInfo: {
        flex: 1,
        paddingLeft: 16,
        paddingVertical: 8,
    },
});